// kbi-save.js — 新增两条 KBI 知识入库
var fs = require('fs');
// 路径随脚本位置解析（不再写死 Administrator），跨用户/跨机器一致
var base = require('./lib/common.js').WORKSPACE_ROOT;

// ========== KI-012 OpenClaw Token优化最佳实践 ==========
var ki012 = [
'# KI-20260629-012 | OpenClaw Token优化与记忆系统最佳实践',
'',
'- **分类**：PROCESS（流程优化）',
'- **来源**：CSDN社区多篇文章综合，2026-06-29',
'- **L1 ROI评分**：适用性(3)×落地难度(2)×影响力(5)×有效期(3)×紧迫度(3) = **90** ✅ 采纳',
'',
'## 摘要',
'',
'### 四大Token消耗源',
'- 系统提示词固定税（SOUL.md/MEMORY.md/AGENTS.md 每次注入）',
'- 会话历史滚雪球（长对话上下文线性增长）',
'- 工具输出垃圾堆积（执行结果24h不过期）',
'- 心跳静默消耗（每次HEARTBEAT_OK也吃token）',
'',
'### 核心优化策略（10条已验证）',
'',
'**1. 上下文修剪（Context Pruning）- 效果最显著**',
'- 默认TTL 1小时→缩至5分钟 + hardClearRatio 0.5',
'- 工具结果失效后立即从上下文剔除',
'- 配置：`"contextPruning": {"mode": "cache-ttl", "ttl": "5m", "softTrimRatio": 0.3, "hardClearRatio": 0.5}`',
'',
'**2. 会话压缩（Session Compaction）**',
'- safeguard(保守)→adaptive(激进)模式',
'- 实测可降低90% token（摘要压缩）',
'- 配合滑动窗口（保留5-20轮对话）',
'',
'**3. 提示词缓存（Prompt Caching）**',
'- 针对Claude系列模型：缓存读取=写入成本×1/10',
'- 心跳设为55分钟（略低于缓存失效1小时），保活缓存',
'',
'**4. Memory分类管理**',
'- 长期记忆：MEMORY.md（只存偏好/规则/铁律，不存项目细节）← 我们刚做了这个',
'- 短期记忆：24h自动清理的临时数据',
'- 自动总结：每10轮对话生成摘要替代完整历史',
'',
'**5. 选择性加载（动态分配比例）**',
'- 系统提示词10%、记忆20%、对话历史40%、工具结果20%、预留10%',
'- 大文件拆分为子文件按需read ← 我们刚做了这个',
'',
'**6. SOUL.md/系统提示词瘦身**',
'- 去掉冗余指令，只留核心人设',
'- 明确要求"精简回复"（已在MEMORY.md规则4）',
'',
'**7. 本地Embedding替代云端API**',
'- memory_search 用本地模型 → 成本归零',
'- 适用场景：知识库检索、记忆搜索',
'',
'**8. 子Agent并发控制**',
'- 默认并发8→降至4',
'- 减少同时间塞进上下文的工具结果量',
'',
'**9. 任务拆解+分步执行**',
'- 一个复杂任务拆成多个小任务',
'- 每次只带相关上下文，减少每次token消耗',
'',
'**10. 模型分层使用**',
'- 简单任务→轻量模型（hy3-preview），复杂任务→全量模型',
'- 心跳/自检/简单查询用便宜模型',
'',
'### 记忆系统架构（OpenClaw Markdown记忆模型）',
'- 持久化：workspace/*.md → 注入为system context',
'- 会话级：LCM压缩→会话摘要（sum_xxx）',
'- 关键设计原则：',
'  1. 长期记忆(规则/偏好/铁律) → MEMORY.md常驻',
'  2. 项目细节(命名/设定/Agent) → 独立文件按需read',
'  3. 会话历史→LCM自动压缩摘要',
'  4. 临时数据→24h自动清理',
'',
'## 我们已做的事',
'- ✅ MEMORY.md 12.8KB→3.9KB（-70%）',
'- ✅ 项目设定拆分到 .learnings/project-reference.md 按需加载',
'- ✅ 进化系统拆分到 .learnings/systems-reference.md 按需加载',
'- ✅ 子Agent降模型 hy3-preview',
'',
'## 待应用',
'- ⬜ 检查当前 contextPruning 配置 → 确认TTL是否可优化',
'- ⬜ SOUL.md 瘦身 → 目前只有29字节已经够瘦',
'- ⬜ 检查 Prompt Caching 是否生效',
'- ⬜ 子Agent并发控制 → 从默认调整',
'',
'## 建议应用目标',
'- **TOOLS.md**：记录token优化清单',
'- **MEMORY.md**：加入记忆分类管理规则',
'- **AGENTS.md**：加入上下文管理最佳实践',
'- **下一次心跳**：检查contextPruning配置状态',
''
].join('\n');

fs.writeFileSync(base + '\\.learnings\\knowledge-inbox\\PROCESS\\KI-20260629-012_Token优化与记忆系统.md', ki012, 'utf8');
console.log('KI-012 saved: Token优化与记忆系统');

// ========== KI-013 OpenClaw 积分/成本管理 ==========
var ki013 = [
'# KI-20260629-013 | OpenClaw API积分与成本管理',
'',
'- **分类**：PROCESS（成本管理）',
'- **来源**：CSDN社区多篇文章+实测经验，2026-06-29',
'- **L1 ROI评分**：适用性(3)×落地难度(1)×影响力(4)×有效期(3)×紧迫度(3) = **108** ✅ 采纳',
'',
'## 核心发现',
'',
'### 成本结构拆解',
'- 历史对话：30-40%（最大头）',
'- 工具结果：20-30%',
'- 系统提示词：15-20%',
'- 模型思考(reasoning)：10-15%',
'- 心跳+元数据：5-10%',
'',
'### 7条省钱铁律',
'',
'**1. 同一任务不要换模型**',
'- 切换模型=缓存失效=全量重写=额外成本',
'- 方案：为每个Agent固定模型（审核专员=hy3, 主控=pool-deepseek-v4）',
'',
'**2. 长任务拆短任务**',
'- 2小时连续对话=100元(实测) → 拆成4个30分钟会话=约40元',
'- 每次新session(或/reset)清空历史=token从头算',
'',
'**3. 会话压缩在token用掉前触发**',
'- 不要等到90%才压缩，50-60%就触发',
'- LCM compaction应在阈值40-50%启动',
'',
'**4. 心跳用最便宜模型**',
'- 心跳检查只是扫描+评判，不需要顶级模型',
'- 用 hy3-preview 或更轻量模型',
'',
'**5. 禁用冗余thinking输出**',
'- reasoning/thinking token也算钱',
'- 简单任务关掉thinking',
'',
'**6. 工具结果triage**',
'- 只保留关键工具结果（exec stdout>100行的截断）',
'- 浏览器screenshot只在需要时拿',
'',
'**7. API聚合平台省钱**',
'- 官方API>聚合平台≈省40%',
'- 但考虑稳定性，当前用pool-deepseek-v4-pro已经较便宜',
'',
'### 我们当前的成本画像（估算）',
'- 主模型：qclaw/pool-deepseek-v4-pro（聚合池，相对便宜）',
'- 子Agent：hy3-preview（轻量）',
'- 心跳：60min间隔（中等频率）',
'- 小说创作：子Agent承担，主控只做调度+质检',
'',
'## 建议应用',
'- **下次心跳**：检查当前model配置+thinking模式是否最优',
'- **大任务**：自动拆分为子Agent并行（已实现sessions_spawn）',
'- **心跳模型**：确认是否可以用更便宜模型',
''
].join('\n');

fs.writeFileSync(base + '\\.learnings\\knowledge-inbox\\PROCESS\\KI-20260629-013_积分与成本管理.md', ki013, 'utf8');
console.log('KI-013 saved: 积分与成本管理');

// Update tracker
var trackerPath = base + '\\.learnings\\kbi-tracker.json';
var tracker = JSON.parse(fs.readFileSync(trackerPath, 'utf8'));
tracker.entries['KI-20260629-012'] = {"roi": 90, "status": "applying", "appliedAt": "2026-06-29", "appliedItems": ["记忆分类管理规则→MEMORY.md", "Token优化清单→TOOLS.md"], "note": "Token优化与记忆系统最佳实践"};
tracker.entries['KI-20260629-013'] = {"roi": 108, "status": "applying", "appliedAt": "2026-06-29", "appliedItems": ["成本结构分析→MEMORY.md", "7条省钱铁律→TOOLS.md"], "note": "积分与成本管理"};
tracker.lastScan = "2026-06-29T07:40:00+08:00";
fs.writeFileSync(trackerPath, JSON.stringify(tracker, null, 2), 'utf8');
console.log('Tracker updated');

console.log('Done. 2 new KBIs saved.');
